### PR TITLE
Use underlying statement instead of executing SQL query

### PR DESCRIPTION
**Pull request by kudryashov-sv**

### CODE REVIEW

**Comment by l3pp4rd** [comment]
Hi, seems like one test is failing https://travis-ci.org/DATA-DOG/go-txdb/jobs/377222564

**Comment by l3pp4rd** [comment]
and please do not add gitignore. use your global gitignore config for your idea or project specific ignores.

**Comment by l3pp4rd** [comment]
I think we can just add go 1.10.x and comment the older ones before 1.7.x.

Though, I'm not sure if it is worth to have the statement opened (it holds the database connection). That was the reason I was closing it. Maybe it is not efficient, but allows to prepare the statement anywhere in code even as a static variable and then use it with different txdb transactions. I'll need to add a test before merging so that I'm sure we are not using flexibility. Since txdb is meant to be used for testing, few milliseconds are not important, in this current implementation it was anyway using the same transaction connection whenever prepared statement was executed, so I think there was no issue with that.

Could you explain the reasoning for this change?

**Comment by kudryashov-sv** [comment]
+ add go 1.10.x

My reason is not performance issues, i work with lib/pq (PostgreSQL) and have code like this:
```
db, _ := sql.Open("txdbp", "ko")
db.Exec(`create table if not exists testtx (id bigserial primary key, value text not null )`)

tx, _ := db.Begin()
defer tx.Rollback()

stmt, _ := tx.Prepare(pq.CopyIn("testtx", "id", "value"))
defer stmt.Close()

stmt.Exec(1, "petr")
stmt.Exec(2, "basil")
stmt.Exec(3, "vova")
stmt.Exec()

tx.Commit()

// expect data:
// id, value
// 1,  'petr'
// 2,  'basil'
// 3,  'vova'
```

It's way to do batch imports into postgres, problem with old version is lines like this: `stmt.Exec(1, "petr")` - executing query `COPY "testtx" ("id", "value") FROM STDIN` with parameters produce error.

**Comment by l3pp4rd** [comment]
OK, makes sense, thanks ;)

**Pull request merged**
